#!/usr/bin/env bash
# PreToolUse (Write|Edit|MultiEdit|NotebookEdit) : règle du STOP d'AGENTS.md, section 1.
# Une fois npm-packages/ ou proto-registry/ édité dans la session (marqueur posé par post-edit.sh),
# toute édition d'un repo qui dépend de @volontariapp/* est refusée jusqu'à publication par la CI.
# Déverrouillage, Lead Dev uniquement : ! .claude/hooks/stop-rule-guard.sh release
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STATE_DIR="$REPO_ROOT/.git/volontariapp-stop-guard"

if [ "$1" = "release" ]; then
  rm -rf "$STATE_DIR"
  echo "Verrou STOP levé pour toutes les sessions."
  exit 0
fi

INPUT=$(cat)
SESSION=$(printf '%s' "$INPUT" | jq -r '.session_id // empty')
FILE=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')
MARK="$STATE_DIR/$SESSION"
{ [ -z "$SESSION" ] || [ -z "$FILE" ] || [ ! -f "$MARK" ]; } && exit 0

case "$FILE" in
  "$REPO_ROOT"/*) ;;
  *) exit 0 ;;
esac
REL="${FILE#"$REPO_ROOT"/}"
TOP="${REL%%/*}"
UPSTREAM=$(sort -u "$MARK" | paste -sd ',' -)

# Nearest package.json between the file and its repository root.
depends_on_volontariapp() {
  local dir
  dir="$(dirname "$FILE")"
  while [ "$dir" != "$REPO_ROOT" ] && [ "${dir#"$REPO_ROOT"/}" != "$dir" ]; do
    if [ -f "$dir/package.json" ]; then
      grep -q '"@volontariapp/' "$dir/package.json"
      return $?
    fi
    dir="$(dirname "$dir")"
  done
  return 1
}

LOCKED=""
case "$TOP" in
  npm-packages)
    # Generated by proto-registry's CI: hand edits are forbidden while a .proto change is pending.
    if grep -qx "proto-registry" "$MARK" && [[ "$REL" == npm-packages/packages/contracts* ]]; then
      LOCKED="contracts générés par la CI de proto-registry"
    fi
    ;;
  proto-registry) ;;
  *)
    depends_on_volontariapp && LOCKED="consommateur de @volontariapp/*"
    ;;
esac
[ -z "$LOCKED" ] && exit 0

REASON="RÈGLE DU STOP (AGENTS.md, section 1) : ${UPSTREAM} a été modifié dans cette session, ${REL} est un ${LOCKED}.
Ne touche à aucun autre repo. Vérifie la compilation et les tests du package amont, crée le changeset (npm-packages) ou lance buf lint / buf breaking (proto-registry), puis rends la main au Lead Dev avec un résumé : il pousse la PR et attend la publication par la CI.
Interdit : contourner ce verrou (sed, cat >, script) ou lancer stop-rule-guard.sh release toi-même."
jq -n --arg reason "$REASON" '{hookSpecificOutput:{hookEventName:"PreToolUse", permissionDecision:"deny", permissionDecisionReason:$reason}}'
exit 0
